config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'register'}

  root :to => "admin/dashboard#index"
  resource :sessions, only: [:new, :create, :destroy]
  delete 'logout' => 'sessions#destroy'

  # Administration
  namespace :admin do
    resources :dashboard

    namespace :inventory do
      resources :items
    end

    namespace :pos do
      resources :sales do
        collection do
          get 'computation'
        end
      end
      resources :reports
    end

    resources :setting_module, only: [:index]

    namespace :setting_module do
      resources :categories
      resources :category_types
      resources :units
    end

  end

  # # API
  # namespace :api do
  #   namespace :v1 do
  #     resources :categories, only: [:index, :create, :destroy, :update]
  #   end
  # end

end

app/models/item.rb
class Item < ActiveRecord::Base

  before_create :generate_item_code

  belongs_to :category_type
  belongs_to :unit

  def item_selected
    self.item_name + " - " + self.unit.name
  end

  private

  def generate_item_code
    begin
      self.item_code = SecureRandom.random_number(999999).to_i
    end while self.class.exists?(item_code: item_code)
  end

end

app/controllers/admin/inventory/items_controller.rb
class Admin::Inventory::ItemsController < Admin::SettingModuleController

  before_action :look_ups, :only => [:new, :edit, :update]
  before_action :set_item_id, :only=> [:show, :edit, :update, :destroy]

  def index
    params[:q] ||= {}

    @q = Item.ransack(params[:q])
    @items = @q.result.all.order("id DESC").paginate(:page => params[:items], :per_page => 10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to "/admin/inventory/items"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to "/admin/inventory/items?update=updated"
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @item.destroy
    redirect_to "/admin/inventory/items?update=success"
  end

  private

  def look_ups
    @category_types = CategoryType.select("id, name").order("name ASC").all
    @units = Unit.select("id, name").order("name ASC").all
	end

  def set_item_id
    @item = Item.find(params[:id])
  end

  def item_params
		params.require(:item).permit(:category_type_id, :item_code, :item_name, :description,
        :unit_id, :price, :sale_price, :stock)
	end

end

app/views/admin/inventory/items/_form.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        h3.panel-title New Item
      .panel-body
        = form_for([:admin, :inventory, @item], :html => {:class => "form-horizontal form-border"}) do |f|
          .form-group
            .col-sm-6
              label for="item_name"  Item Name
              = f.text_field :item_name, :class=>"form-control", placeholder: "Item Name"

            .col-sm-6
              label for="category_type_id"  Category Type
              =f.select(:category_type_id, options_from_collection_for_select(@category_types,"id","name", f.object.category_type_id),{},:class =>"form-control chosen")

          .form-group
            .col-sm-4
              label for="unit_id"  Unit
              =f.select(:unit_id, options_from_collection_for_select(@units,"id","name", f.object.unit_id),{},:class =>"form-control chosen")

            .col-sm-4
              label for="price"  Price
              = f.text_field :price, :class=>"form-control"

            .col-sm-4
              label for="sale_price"  Sales Price
              = f.text_field :sale_price, :class=>"form-control"

          .form-group
            .col-sm-6
              label for="stock"  Stock
              = f.text_field :stock, :class=>"form-control"

            .col-sm-6
              label for="description" Description
              = f.text_area :description, :class=>"form-control"

          .row
            .col-md-12
              hr
              .btn-group.pull-right
                a.btn.btn-default href="/admin/inventory/items" Cancel
                = f.submit "Save", :class => "btn btn-success"

javascript:
  $(".chosen").chosen();

app/views/admin/inventory/items/index.html.slim
.col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
  h4.page-header Inventory

  .row
    .col-md-8
      .row
        .col-xs-6
        .col-xs-6
          .btn-group.pull-right
            = link_to '', class: 'btn btn-sm btn-warning'
            a.btn.btn-sm.btn-primary href="/admin/inventory/items/new" Add

      br
      .panel.panel-default
        .panel-heading
          h3.panel-title Items
        .panel-body
          .table-responsive
            table.table.table-hovered.table-striped
              thead
                tr
                  th Item Code
                  th Item Name
                  th Category
                  th Unit
                  th Price
                  th Sale Price
                  th Stock
              tbody
                -if @items == []
                  tr
                    td colspan="7" No records
                -else
                 - @items.each do |item|
                   tr
                    td= item.item_code
                    td= item.item_name
                    td= item.category_type.name
                    td= item.unit.name
                    td= number_to_currency(item.price, unit: "₱")
                    td= number_to_currency(item.sale_price, unit: "₱")
                    td
                      - if item.stock.to_i <= 50
                        .warning= item.stock
                      -else
                        = item.stock

              =will_paginate @items, :param_name=>"items",:previous_label => '<i class="fa fa-chevron-left"></i>'.html_safe, :next_label => '<i class="fa fa-chevron-right"></i>'.html_safe
    .col-md-4
      .panel.panel-default
        .panel-heading
          h3.panel-title Filter
        .panel-body
          = search_form_for @q, url: admin_inventory_items_path, html: { class: 'form-vertical' } do |f|
            .panel-body
              .form-group
                = f.label 'Item Code'
                = f.search_field :item_code_eq, class: 'form-control input-sm'

              .form-group
                = f.label 'Item Name'
                = f.search_field :item_name_eq, class: 'form-control input-sm'

            = link_to 'Cancel', admin_inventory_items_path, class: 'btn btn-default btn-block'
            = f.submit "Search", class: 'btn btn-primary btn-block'

app/views/admin/inventory/items/new.html.slim
.col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
  h4.page-header Inventory
  .breadcrumb-wrapper
    ol.breadcrumb
      li Item
      li.active Add New
  section#main-content.animated.fadeInUp
    = render 'form'