config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'register'}

  root :to => "admin/dashboard#index"
  resource :sessions, only: [:new, :create, :destroy]
  delete 'logout' => 'sessions#destroy'

  # Administration
  namespace :admin do
    resources :dashboard

    namespace :inventory do
      resources :items
    end

    namespace :pos do
      resources :sales do
        collection do
          get 'computation'
        end
      end
      resources :reports
    end

    resources :setting_module, only: [:index]

    namespace :setting_module do
      resources :categories
      resources :category_types
      resources :units
    end

  end

  # # API
  # namespace :api do
  #   namespace :v1 do
  #     resources :categories, only: [:index, :create, :destroy, :update]
  #   end
  # end

end

app/controllers/admin/pos/reports_controller.rb
class Admin::Pos::ReportsController < Admin::SettingModuleController

  def index
    params[:q] ||= {}

    if params[:q][:created_at_lteq].present?
      params[:q][:created_at_lteq] = params[:q][:created_at_lteq].to_date.end_of_day
    end

    @q = Sale.ransack(params[:q])
    @sales = @q.result.all.page(params[:page])

    @total_sale = @sales.sum(:total)
  end

end

app/controllers/admin/pos/sales_controller.rb
class Admin::Pos::SalesController < Admin::SettingModuleController

  before_action :look_ups, :only => [:new, :edit, :update]

  def index
    @transactions = Sale.all.order("id DESC").paginate(:page => params[:transactions], :per_page => 10)
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    if @sale.save

      # Update Stock in Inventory {items table}
      @quantity = @sale.quantity

      @item = Item.find(@sale.item_id)
      @updated_stock = (@item.stock.to_i - @quantity.to_i)

      @item.update_attributes(:stock => @updated_stock.to_i)

      redirect_to "/admin/pos/sales"
    else
      render :new
    end
  end

  def computation
    item_id = params[:item_id]
    item = Item.select('id, item_name, sale_price').where(id: item_id).first

    @item_price = item.sale_price.to_f

    respond_to do |format|
      format.js { render :action => "computation" }
    end

  end

  private

  def look_ups
    @items = Item.select("id, item_name, unit_id").order("item_name ASC").all
    @units = Unit.select("id, name").order("name ASC").all
  end

  def sale_params
		params.require(:sale).permit(:transaction_code, :item_id, :note, :quantity, :price, :total)
	end

end

app/controllers/admin/pos_controller.rb
class Admin::PosController < AdminController

  def index
  end

end

app/views/admin/pos/reports/index.html.slim
.col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
  h4.page-header Reports

  .row
    .col-lg-8
      .panel.panel-default
        .panel-heading
          h3.panel-title Sales Report
        .panel-body
          .table-responsive
            table.table.table-hovered.table-striped
              thead
                tr
                  th Transaction Code
                  th Item Code
                  th Price
                  th Date Purchased
              tbody
                -if @sales == []
                  tr
                    td colspan="7" No records
                -else
                 - @sales.each do |sale|
                   tr
                    td= sale.transaction_code
                    td= sale.get_item_code
                    td= number_to_currency(sale.total, unit: "₱")
                    td= format_date(sale.created_at)




    .col-lg-4
      .panel.panel-default
        .panel-heading
          h3.panel-title Summary
        .panel-body
          ul.list-group
            li.list-group-item
              span.badge= number_to_currency(@total_sale, unit: "₱")
              | Total Sales



      .panel.panel-default
        .panel-heading
          h3.panel-title Sales Date
        .panel-body
          = search_form_for @q, url: admin_pos_reports_path, html: { class: 'form-vertical' } do |f|
            .panel-body
              .form-group
                = f.label 'FROM'
                = f.search_field :created_at_gteq, class: 'form-control input-sm date1'

              .form-group
                = f.label 'TO'
                = f.search_field :created_at_lteq, class: 'form-control input-sm date2'
            = link_to 'Cancel', admin_pos_reports_path, class: 'btn btn-default btn-block'
            = f.submit "Search", class: 'btn btn-primary btn-block'


javascript:
  $(document).ready(function(){
    $('.date1').datepicker({ format: 'yyyy-mm-dd' });
    $('.date2').datepicker({ format: 'yyyy-mm-dd' });
  });